name: walletconnectconfig
key: ------- !! ---------
wallets:
  {"wallets":
    [{"name":"",
      "attributes":
        {"addr":"",
         "network":"",
         "chainid": 1
        }
     },]
  }
